services:

  pg_rest_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pg_rest_backend
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      - .:/app
      - /app/node_modules
